# Generated by Django 5.2.5 on 2025-08-07 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateField(default=datetime.date.today, help_text='Date when the change occurred')),
            ],
            options={
                'verbose_name': 'Change',
                'verbose_name_plural': 'Changes',
                'db_table': 'forms_change',
                'ordering': ['-change_date'],
            },
        ),
    ]
